[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "energyplus-viewfactors"
dynamic = ["version"]
description = 'Calculate view factors for EnergyPlus'
readme = "README.md"
requires-python = ">=3.8"
license = "BSD-3-Clause"
keywords = []
authors = [
  { name = "Jason W. DeGraw", email = "jason.degraw@gmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "click",
  "pathvalidate",
  "tkmacos ; platform_system == \"Darwin\"",
]

[project.urls]
Documentation = "https://github.com/building-physics/energyplus-viewfactors#readme"
Issues = "https://github.com/building-physics/energyplus-viewfactors/issues"
Source = "https://github.com/building-physics/energyplus-viewfactors"

[project.scripts]
energyplus-viewfactors = "energyplus_viewfactors.cli:energyplus_viewfactors"

[project.gui-scripts]
epvf = "energyplus_viewfactors.gui:epvf"

[tool.hatch.version]
path = "src/energyplus_viewfactors/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/energyplus_viewfactors tests}"

[tool.coverage.run]
source_pkgs = ["energyplus_viewfactors", "tests"]
branch = true
parallel = true
omit = [
  "src/energyplus_viewfactors/__about__.py",
]

[tool.coverage.paths]
energyplus_viewfactors = ["src/energyplus_viewfactors", "*/energyplus-viewfactors/src/energyplus_viewfactors"]
tests = ["tests", "*/energyplus-viewfactors/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
